<<<<<<< HEAD
blank_issues_enabled: true
contact_links:
  - name: ðŸ“„ Docs
    url: https://docs.ultralytics.com/
    about: Full Ultralytics YOLOv8 Documentation
  - name: ðŸ’¬ Forum
    url: https://community.ultralytics.com/
    about: Ask on Ultralytics Community Forum
  - name: ðŸŽ§ Discord
    url: https://ultralytics.com/discord
    about: Ask on Ultralytics Discord
=======
# Ultralytics ðŸš€ AGPL-3.0 License - https://ultralytics.com/license

blank_issues_enabled: true
contact_links:
  - name: ðŸ“„ Docs
    url: https://docs.ultralytics.com/
    about: Full Ultralytics YOLO Documentation
  - name: ðŸ’¬ Forum
    url: https://community.ultralytics.com/
    about: Ask on Ultralytics Community Forum
  - name: ðŸŽ§ Discord
    url: https://ultralytics.com/discord
    about: Ask on Ultralytics Discord
  - name: âŒ¨ï¸ Reddit
    url: https://reddit.com/r/ultralytics
    about: Ask on Ultralytics Subreddit
>>>>>>> 0e451281e978a7c5f581cc5d9bb3d0f62e0bc632
